### ISSUE TITLE
Does not load related dlls.

### ISSUE THREAD

**Issue by mansabbloch** [MarekPokornyOva/BlazorLazyLoad#1]
It loads lazyLoaded.dll successfully when copied in _framework/_bin but it requires an other dll named 'netstandard.dll' which I think is being resolved incorrectly. In first place there should be a solution to build and copy all lazyload dlls.

**Comment by MarekPokornyOva** [comment]
Are you refering Sample or your own test case?
LazyLoaded.dll from sample references mscorlib, Microsoft.AspNetCore.Components and Microsoft.Extensions.DependencyInjection.Abstractions. All of those are already loaded in AppDomain during the main assembly (BlazorApp) load. MetadataAssemblyDependencyResolver watches for already loaded assemblies and should not try to load those referenced assemblies.

Please note: The assembly in Samples\01\LazyLoadedArea\bin\\...\netstandard2.1\LazyLoaded.dll (1) differs from the one in Samples\01\LazyLoadedArea\bin\\...\netstandard2.1\dist\\_framework\\_bin\LazyLoaded.dll (2). The first one is build with standard compiler (and references netstandard) while the second one is optimized to be used in Mono (and references mscorlib). You need to use the second one; unfortunatelly this was not described well in Usage section, hopefully it's clearer now.
If you'd like to use not linked version, you need to copy all referenced/needed assemblies manually, this is not in the solution scope.

Did that help or can you describe your case deeper for further investigation?

**Comment by mansabbloch** [comment]
Thanks for the answer. It helped.
