### ISSUE TITLE
Documentation for a dynamic download of a module at runtime

### ISSUE THREAD

**Issue by radderz** [MarekPokornyOva/BlazorLazyLoad#2]
What would be great to have documentation/samples for is how to build a dynamic module system.

i.e. adding a module at runtime that is only known due to an API request.

If the sample had an API hosted blazor wasm site with the "module" being loaded dynamically from an API location that returns the dynamic manifest file and loads the page that'd be perfect. The example could just have some files sitting in the API as content, as there is no technical difficulty between that and hitting a repo to get those files.

i.e. have a controller that takes in a package id or name, and picks that dynamic package from the content folders. Could have two packages, one that shows a page with module 1, and another with module 2, with a drop down picking which one to display.

**Comment by MarekPokornyOva** [comment]
@radderz, what do you mean "dynamic module system"?
This solution allows you to build any modularity you like. Please look at \Samples\01\BlazorApp\AreaAssemblyLazyLoadResolver.cs. The resolver allows you to do/lazyload whatever you like based on requested uri. This service is responsible for resources preparation, the rest of page loading will be handled by standard Blazor functionality.

It's easy to build a resolver handling any custom manifest file. Then it's you responsibility to download the assemblies from any repository you like (LAN server, CDN, fallbacks, ...).
